//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaAngela
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int idPedido { get; set; }
        public int IdCliente { get; set; }
        public int IdDetalleSubpedido { get; set; }
        public decimal CostoEnvio { get; set; }
        public int IdEstadoPedido { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual DetalleSubpedido DetalleSubpedido { get; set; }
        public virtual EstadosEnvio EstadosEnvio { get; set; }
    }
}
